baseURL = "/"
languageCode = "en-us"
title = "Siddharth Arumugam - Blog"

enableRobotsTXT = true

# Theme config
paginate = 5
theme = "terminal"

[params]
  contentTypeName = "posts"

  themeColor = "blue"

  fullWidthTheme = false
  centerTheme = true

  autoCover = false
  showLastUpdated = false
  readingTime = false
  Toc = false

  favicon = "favicon.ico"
  # Cover image for home page
  homeCover = "https://cdn.jsdelivr.net/gh/0xMrNight/blog-images@master/commons/blog-cover.jpg"

[params.twitter]
  creator = "0xMrNight"
  site = "0xMrNight"

[languages]
  [languages.en]
    [languages.en.params]
      languageName = "English"
      title = "Siddharth Arumugam"
      subtitle = ""
      owner = "Siddharth Arumugam"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Mr Night"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
